server:
  port: '8080'
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: log
          uri: 'http://${REGLOG_SERVICE:localhost}:8081/'
          predicates:
            - Path= /login/**
        - id: reg
          uri: 'http://${REGLOG_SERVICE:localhost}:8081/'
          predicates:
            - Path= /registration/**
        - id: reception
          uri: 'http://${RECEPTION_SERVICE:localhost}:8083/'
          predicates:
            - Path= /reception/**
        - id: doctor
          uri: 'http://${DOCTOR_SERVICE:localhost}:8082/'
          predicates:
            - Path= /doctor/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${EUREKA_SERVER:localhost}:8761/eureka'